# Rendering a collection, modules

## Rendering Collections
Instead of hardcoding index values to render objects from arrays, we can generate React elements from array objects using the map function. For example:
```
<ul>
    {notes.map(note => <li>{note.content}</li>)}
</ul>
```

Because the code generating the *li* tags is JavaScript, it must be wrapped in curly braces in a JSX template just like all other JavaScript code.

## Key attribute
The code from the above section will cause a warning in the console. The list items generated by the `map` method must each have a unique key value: an attribute called `key`.
```
<ul>
    {notes.map(note => 
        <li key={note.id}>            
            {note.content}
        </li>
    )}
</ul>
```

React uses the key attributes of objects in an array to determine how to update the view generated by a component when the component is re-rendered.

## Map
`map` always creates a new array, the elements of which have been created from the elements of the original array by *mapping*: using the function given as a parameter to the `map` method.

The full signature for arrow functions is:
```
array.map((element, index(optional), array(optional)) => { ... })
```

## Anti-pattern: Array indexes as keys
We could have used the array indexes as keys. However, this is **not recommended** and can create undesired problems, even if things seem to work fine.

When rendering a list of items, like we did using `map` above, make sure to use a *permanent* and *unique* identifier for the key attribute, or generate one if you don't have one for each already.

## Refactoring Modules
Common practice in React is to declare each component in their own file as an ES6 module.

In smaller applications, components are usually placed in a directory called *components*, which is in turn placed within the *src* directory. The convention is to name the file after the component.

Note that when importing our own components, their location must be given *relative to the importing file*: `'./components/Note'`
